
name: tvm-bot
on:
  pull_request_review:
    types:
      - submitted
  issue_comment:

concurrency:
  group: merge-${{ github.event.pull_request.number }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  run-tvm-bot:
    permissions:
      actions: write
      checks: write
      contents: write
      id-token: write
      issues: write
      pull-requests: write
      statuses: write
    if: ${{ github.event.issue.pull_request && github.repository == 'apache/tvm' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: show ci/scripts/github/github_tvmbot.py
        run: |
          set -eux
          if ! [ -f ci/scripts/github/github_tvmbot.py ]; then
            echo "Error: ci/scripts/github/github_tvmbot.py not found"
            exit 1
          fi
          cat ci/scripts/github/github_tvmbot.py
      - name: Run tvm-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACTIONS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          TVM_BOT_JENKINS_TOKEN: ${{ secrets.TVM_BOT_JENKINS_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          ISSUE_COMMENT: ${{ toJson(github.event.comment) }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          set -eux
          python ci/scripts/github/github_tvmbot.py --pr "$PR_NUMBER" --run-url "$RUN_URL" --trigger-comment-json "$ISSUE_COMMENT"
